aptitude:
  environment: staging
spring:
  datasources:
    driverClassName: org.h2.Driver
    url: jdbc:h2:./employee
    platform: all
  main:
    bannerMode: "off"
#logging:
#  level:
#    root: "ERROR"